### ISSUE TITLE
Conform passes in non-recognized props to <input> fields

### ISSUE THREAD

**Issue by lime517** [edmundhung/conform#145]
When using Conform within [Remix Epic Stack](https://github.com/epicweb-dev/epic-stack/), I receive warnings for three different props that Conform passes in. 

```
Warning: React does not recognize the `initialError` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `initialerror` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

This same error is repeated for `descriptionId` and `errorId`.

I believe the solution is to just rename those props to be 100% lowercase, but I'd love to understand if there's a particular reason behind this naming scheme.

**Comment by edmundhung** [comment]
Hi @lime517. Thanks for raising this up! 

These properties should not be set on the element. It should use the [conform](https://conform.guide/api/react#conform) helper to derive the properties the element needed. The issues on the EPIC stack seems to be caused by how the properties were passed to each field and then spread on the element directly. 

https://github.com/epicweb-dev/epic-stack/pull/77 should fixes it.

**Comment by lime517** [comment]
@edmundhung  - ahh, that makes a lot more sense! Thank you!
