### ISSUE TITLE
How to deal with number inputs?

### ISSUE THREAD

**Issue by jansedlon** [edmundhung/conform#175]
Hi again!

I wonder how to deal with number inputs? As per type="number" input spec, it has an available property call `valueAsNumber`. I know that conform does not coerce anything #107 but if it's a native behaviour, why not do it? I saw checkbox and radio specific code in this library so why not number? Is this something I could help you with?

**Comment by edmundhung** [comment]
Hi @jansedlon 

Really appreciate for the offers! The main issue is the same as the checkbox / radio buttons. Since the formData will serialize everything as string except Files. Our server has no idea if a particular entry comes from a specific input type and coerce it on the server side.

I have been exploring a way to reuse the input attributes for validation and coercions based on the input attributes which [I shared on Remix Conf](https://www.youtube.com/watch?v=Y7G6n3kZC9E) last month. This does not work with the Conform solution yet. I am also unsure whether this should be a standalone validation solution or if it worths integrating with Conform tightly  and potentially figure out a way to enhance zod with similar capabilities.

**Comment by jansedlon** [comment]
Hmmm, you're right, probably solution like `zod-form-data` is good enough for now 🤔

**Comment by edmundhung** [comment]
Closing this for now. Feel free to reopen it if you have any new suggestion over this.
