### ISSUE TITLE
0.7.0 not working with remix blues-stack

### ISSUE THREAD

**Issue by MoSattler** [edmundhung/conform#188]
Not sure what is happening, but when I try to run the [build script](https://github.com/remix-run/blues-stack/blob/main/package.json#L8) with the new version, I get this error:

```
✘ [ERROR] Could not resolve "@conform-to/react/helpers"

    app/routes/creator.dashboard.tsx:2:22:
      2 │ import { input } from "@conform-to/react/helpers";
        ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The path "./helpers" is not exported by package "@conform-to/react":

    node_modules/@conform-to/react/package.json:10:12:
      10 │   "exports": {
         ╵              ^

  You can mark the path "@conform-to/react/helpers" as external to exclude it from the bundle, which will remove this error.
```

any idea?

**Comment by edmundhung** [comment]
Hi @MoSattler, it's because Conform now restrict what's exposed with the new [exports](https://github.com/edmundhung/conform/blob/main/packages/conform-react/package.json#L10-L18) configuration for ESM and importing from an internal file is no longer consider valid.

Is there any reason why you are not importing it through the `conform` namespace object? IMO, all helpers are similar and share the same core logic so importing individually function [will not save you much space](https://github.com/edmundhung/conform/blob/main/packages/conform-react/helpers.ts#L164-L185).

**Comment by edmundhung** [comment]
Try this:

```tsx
// Import the `conform` helper
import { conform } from '@conform-to/react';

// Use it with JSX like this:
<input {...conform.input(fieldConfig)} />
```

Sorry if it wasn't clear on the documentation. Improving the docs is now my main focus after the release.
