### ISSUE TITLE
useFieldList initializes with one item

### ISSUE THREAD

**Issue by jansedlon** [edmundhung/conform#205]
Hi Edmund. May I ask why `useFieldList` initialises with one empty value?

Im referring to this code
https://github.com/edmundhung/conform/blob/cfc41f3417faee5a0201a2a9cdd1b73bf3eb0944/packages/conform-react/hooks.ts#L709

In order to **not** start with one empty value, I need to specifically put empty array in `defaultValue` in `useForm` like this
```ts
useForm({
  defaultValue: {
    exercises: []
  }
})
```

I think that starting with 0 values should be the default behaviour. Is there any reason you decided to go with 1 empty?

**Comment by edmundhung** [comment]
Hi @jansedlon,

It defaults to one item mainly because I consider it the most common setup. But you are not the first one questioning this. I also find it awkward to set an empty array in this case.

It seems like both formik and react-hook-form defaults to empty array as well. Happy to make this change on the next version. Thanks for raising this up.

**Comment by jansedlon** [comment]
That would be great 🙏

**Comment by EugenEistrach** [comment]
Yeah just stumbled with this myself right now. Also the docs provide an example where you [show how to ensure that list uses one item as default](https://conform.guide/intent-button#triggering-an-intent) and that confused me even more because I assumed the default behaviour would be that it starts with 0 items.

**Comment by edmundhung** [comment]
Fixed on [v0.8.0](https://github.com/edmundhung/conform/releases/tag/v0.8.0).
