### ISSUE TITLE
Make a PE reset button

### ISSUE THREAD

**Issue by kentcdodds** [edmundhung/conform#217]
The `<button type="reset">Reset</button>` works well for resetting native HTML forms. I think it's awesome that it's progressively enhanced. I also think it's awesome that `list.append` and `list.remove` are progressively enhanced as well.

Unfortunately when using these together, they do not progressively enhance. Any ideas on how to make this work?

**Comment by edmundhung** [comment]
The native reset button does not work well in a NoJS environment because the initial value of the form is keep changing as you click on each button and the form values are persisted by using as the previous form data as the initial value.

As an alternative solution, Conform could provide a `reset` intent that you can set on the button and have it working both before and after JS is loaded.

**Comment by kentcdodds** [comment]
Yes, this would be super 👍

**Comment by edmundhung** [comment]
This is now possible with v1.0.0 through a new reset intent. Checkout the docs here: https://conform.guide/intent-button
