### ISSUE TITLE
Error in useFieldset is not propagated

### ISSUE THREAD

**Issue by jansedlon** [edmundhung/conform#233]
Hi. I'm not entirely sure what is happening. I might be wrong somewhere because i don't understand something but it also might be a bug.

I have a fieldlist and fieldset. In a fieldset, there's 3 inputs. Name, notes and templateId select. Name and templateId are required fields. However, when I submit the form, only name get's the error, not the templateId.

Here's sample repo
[CodeSandbox](https://codesandbox.io/p/sandbox/epic-cache-ztdt9x)

Try submit the form and you'll see that the last input does not have any error. The code is simplified a lot but it's just for a showcase

**Comment by edmundhung** [comment]
Hi @jansedlon, 

It's because of the hidden input in your `<Select />` component. Try changing it from `<input type="hidden" {...} />` to `<input hidden {...} />` and it will work. I understand this is confusing. Below you can find a detailed explanation. I will aso improve the integration docs as soon as I can.

#### What happened?
The custom select component renders an input with type `hidden`. Its value is captured by FormData correctly. The result of `parse(formData)` is correct as well with the expected error message. But the error of that particular field is not populated.

#### Why?
Conform relies on the constraint validation mechanism heavily. To populate the error, it set the error message on the input element, then trigger the `invalid` event and finally populate the error message.

But, this mechanism does not apply in some situations. For example, as input with type hidden was not meant for user input. As the value is not changable, there is no need for the browser to validate it. The `invalid` event will not be triggered and no error could be captured. This applys to both `disabled` or `readOnly` input as well (Except the `hidden` attribute 😅 ). 

#### I am using a component library and it is using input with type hidden

Sometimes you just can't change the implementation. One solution is to bring your own hidden input:

```tsx
import Select from 'some-component-library';

function MyCustomSelect() {
  return (
    <>
      {/* This is the input that will be validated by Conform */}
      <input name="field-name" hidden />
      <Select
        {/* Don't pass any name to Select */}
      />
    </>
  );
}
```

This is basically the approach I demonstrated on the [integration] guide. The integration hopefully will be way simplier when the new [<selectmenu />](https://www.smashingmagazine.com/2023/06/advanced-form-control-styling-selectmenu-anchoring-api/) element is widely adopted in the future 😅

**Comment by jansedlon** [comment]
That's great explanation, thank you very much 🙏 And sorry for taking your time
