### ISSUE TITLE
Errors are not correctly reflected

### ISSUE THREAD

**Issue by binajmen** [edmundhung/conform#293]
### Describe the bug and the expected behavior

When submitting a form, the parse in `onValidate()` returns the expected results (I have errors), but these errors are not reflected in the fields (coming from `useForm()`).

```ts
  const [updateForm, fields] = useForm({
    lastSubmission,
    onValidate({ formData }) {
      console.log(parse(formData, { schema: updateSchema }));
      return parse(formData, { schema: updateSchema });
    },
  });

  console.log(fields.accounts);
```

<img width="366" alt="Screenshot 2023-09-25 at 14 48 55" src="https://github.com/edmundhung/conform/assets/15611419/63ced152-e37b-4bd0-8566-ea04ff05c5fa">

### Conform version

0.9.0

### Steps to Reproduce the Bug or Issue

See above

### What browsers are you seeing the problem on?

Chrome

**Comment by edmundhung** [comment]
This is indeed the expected behavior. As I see that you are logging the field with the name `account`, it  populates error messages only if there is an error with the name `account` as well. This happens mainly when you are dealing with group level error. For example, imagine there is an refine on your account schema that validate if it's validity like this: 

```tsx
import { z } from 'zod';

const AccountSchema = z
  .object({
    code: z.string(),
    name: z.string(),
    type: z.string(),
  })
  .refine(account => /* some condition */, 'Invalid account');

const schema = z.object({
  accounts: z.array(AccountSchema),
});
```

The group error will be reflected on the account field errors. If you need to access those messages logged on the screenshot, you need to retrieve the correspond field using a combination `useFieldList` and `useFieldset` as demonstrated on the [remix example](https://conform.guide/examples/remix).
