### ISSUE TITLE
Server-side errors not working in Remix

### ISSUE THREAD

**Issue by osamaaaaa** [edmundhung/conform#372]
### Describe the bug and the expected behavior

Hi,

I'm experiencing a specific issue when using conform in a Remix application. The problem arises during server-side validation: while the `initialError` property correctly displays validation errors, the `error` and `errors` properties remain undefined. This occurs when using both the `Form` and `fetcher.Form` components from Remix.

Through testing, I identified that Loaders ([Remix docs](https://remix.run/docs/en/main/route/loader)) might be the root cause. Without these loaders, `error` and `errors` properties populate correctly, and error messages display in the UI as intended. However, these loaders are crucial for my application.

For reference, here's a minimal reproduction of the issue: [StackBlitz](https://stackblitz.com/edit/remix-run-remix-soopfq?file=app%2Froutes%2F_index.tsx)

Any insights or solutions would be greatly appreciated. Thank you!

### Conform version

0.9.1

### Steps to Reproduce the Bug or Issue

1. Open the [StackBlitz](https://stackblitz.com/edit/remix-run-remix-soopfq?file=app%2Froutes%2F_index.tsx) link
2. Submit the empty form using the `Save` button in the preview window
3. Notice how the `fields.name` output shows the error message in `initialError` but there is no `error` or `errors` defined
4. Remove (or comment out) the loader from the `_index.tsx` file, save changes and refresh the preview window
5. Submit the empty form again and see the error message shown

### What browsers are you seeing the problem on?

Chrome

### Screenshots or Videos

https://github.com/edmundhung/conform/assets/37254654/3a531ca5-d0ad-4973-a16a-ba640bab18e4

**Comment by edmundhung** [comment]
Hi @osamaaaaa. I am sorry for the trouble. There is a limitation in the current version that blocks error update when the field is disabled and because remix navigation state goes from `idle` -> `submitting` -> `loading` -> `idle`. When you have a loader and it reaches the `loading` state, Conform already receive the updated submission and try to update the error while all your fields are disabled because of `navigation.state !== 'idle'`.

This limitation will be removed very soon. But for now, you can switch the isPending logic to `navigation.state === 'submitting' && navigation.formAction === contextualFormAction` so it only disables the fields during the `submitting` state.

**Comment by osamaaaaa** [comment]
Thanks for the clarification @edmundhung! I really appreciate it. I'll switch my `isPending` logic as a workaround for now but really keen to try out the fix once the limitation is removed. Feel free to close this issue now or after the limitation has been removed.

**Comment by edmundhung** [comment]
This should be resolved in [v1.0.0](https://github.com/edmundhung/conform/releases/tag/v1.0.0).
