### ISSUE TITLE
Show error validating object from zod client-side

### ISSUE THREAD

**Issue by danestves** [edmundhung/conform#48]
Currently I have an object that is being validated to know if is empty or not (I'm using a combo box) the error is coming from server-side perfectly but if I use client-side I can see the error on `onValidate` but is not getting the value inside `author.error` on client-side for some reason 🤔 

![CleanShot 2022-11-26 at 18 43 16](https://user-images.githubusercontent.com/31737273/204111541-5580ed2e-8c84-4a8e-bbd9-f321763906a7.png)

**Comment by danestves** [comment]
If I'm not wrong the error is not showing because the "field" is not on the HTML right? But what happen when you are trying to validate a whole object?

**Comment by edmundhung** [comment]
,Hi @danestves,

> Currently I have an object that is being validated to know if is empty or not (I'm using a combo box) the error is coming from server-side perfectly but if I use client-side I can see the error on onValidate but is not getting the value inside author.error on client-side for some reason thinking

Can you provide a bit more details about your combox box setup?

> If I'm not wrong the error is not showing because the "field" is not on the HTML right? But what happen when you are trying to validate a whole object (only validate that the object is not empty)?

Correct. Currently Conform does not do anything for you, you can create a dummy button to capture a particular error if it does not have a proper input field, i.e.

```html
<button name="author" hidden />
```

We use dummy button here as it will not contribute to the result form data. It will act as a placeholder that hold the error message and notify conform through the invalid event. This is a limitation with the current implementation which fully relies on the DOM without using react context. Please also note that the browser will click on the first submit button in the dom when the user is pressing "enter", it would be better to put the dummy button after the actual submit button, or, put another (hidden) submit button before it.

Conform might creates these dummy buttons for you in the future. However, there are still minor issue like introducing side effect for some CSS selectors even the buttons are hidden and so I am still looking for a better solution.

**Comment by danestves** [comment]
Hi @edmundhung ,

> Can you provide a bit more details about your combox box setup?

I'm using the one provided by Headless UI https://headlessui.com/react/combobox 

PD: if you have a better library or something more "native" will be happy to use it

**Comment by edmundhung** [comment]
I feel like I might have misunderstood your question.

> Currently I have an object that is being validated to know if is empty or not (I'm using a combo box) 

What is the shape of the `author` field? By `an object`, do you mean something like this?

```ts
interface Schema {
  author: {
    // ... some properties, e.g. name / email
  };
}
```

I am curious how you are mapping the `author` field to a combobox. (Maybe you got an hidden input name being `author` with a stringified JSON as value?)

> I'm using the one provided by Headless UI https://headlessui.com/react/combobox

Although I am still unsure about your problem, one thing to note here is that the hidden input setup suggested in the [documentation](https://headlessui.com/react/combobox#using-with-html-forms) will not work with Conform due to 2 main issues:

1. `<input type="hidden" />` is not a candidate of Constraint Validation as it is designed for server injected value instead of user input, the browser skips validating the input as per the specification. If you try to set a custom error to the element, it will also be ignored by the browser silently. 
2. The way value is updated is not compliant with how native inputs work. When you type or select an option on native input, the browser updates the value on the element and then dispatch native dom event such as `input` or `change` event. However, this isn't how most of the custom UI components are implemented. It neither dispatch DOM events nor trigger the callback at the right time (i.e. The component `onChange` callback is triggered before the value is set on the input) 

To fix this, you need to use [useControlledInput](https://conform.guide/api/react#usecontrolledinput) with the Combox component.

Let me work on a detail example for integrating with `headless-ui` tomorrow.

**Comment by edmundhung** [comment]
Hi @danestves,

I hope this [headless-ui example](https://conform.guide/examples/headless-ui) is useful for you.

Unfortunately, all 4 components provided requires additional integration. It is a bit disappointed `<Switch />` are not implemented with a checkbox and `<RadioGroup />` are not actually radio buttons 😓

**Comment by brandonpittman** [comment]
React Aria's `useSwitch` lets you render a checkbox. 😄 

https://react-spectrum.adobe.com/react-aria/useSwitch.html

**Comment by danestves** [comment]
Thank you very much @edmundhung indeed that's helpful!! I'm only using Headless for the Combobox, was thinking in another library but HUI was the perfect fit for it 😅 now is working 😀

**Comment by danestves** [comment]
I want to add that is just working :D and I'm very happy for this

![Input inside HTML](https://user-images.githubusercontent.com/31737273/206879553-16306944-935c-4665-8215-ee64eb62db1c.png)

**Comment by edmundhung** [comment]
FYI, I have just released a new API called `useInputEvent` that gives a bit more flexibility and also a wider range of event support (e.g. focus / change event).

You can check the [integrations](https://conform.guide/integrations) guide for details.

I am closing this for now but feel free to reopen it if you need any support 😄
