### ISSUE TITLE
Validation triggers when rendering an input conditionally

### ISSUE THREAD

**Issue by brandonpittman** [edmundhung/conform#49]
https://user-images.githubusercontent.com/967145/205237289-fb36f00e-a3f9-4d12-8719-2a29e858ebec.mp4

I've got some inputs that only render after the user clicks a button to start editing. Whenever the input renders, Conform fires the validation, adds the `data-conform-touched` attribute, and triggers the error message. 

If I don't conditionally render the input, none of that happens.

Is this just me doing something stupid or does it sound like a bug?

**Comment by edmundhung** [comment]
Hi @brandonpittman, good question!

Here is an example [codesandbox](https://codesandbox.io/s/conform-conditional-input-xhw552?file=/app/routes/index.tsx) that render the input conditionally.

> I've got some inputs that only render after the user clicks a button to start editing. Whenever the input renders, Conform fires the validation, adds the data-conform-touched attribute, and triggers the error message.

It depends on how your form and button is setup. As Conform does not mark all inputs as touched unless a submission with type `submit` is received. The problem is very likely caused by how your button is configured here.

There are 2 solutions (both demonstrated on the example above). 
1. Non-submit button that update in-memory state (i.e. `<button type="button" />`)
2. Make it a [command button](https://conform.guide/submission#command-button) with custom type. This requires a bit more setup but your button will now work before JS. 

However, your screenshot looks more like conditionally rendering a form to me actually. How about making the inner form a component and your edit button a link that update the search params and render the form component conditionally?

**Comment by brandonpittman** [comment]
@edmundhung 

It's actually conditionally rendering the submit button, which seems to be causing the issue. When `isEditing` is `false`, it renders a regular button, and then when `isEditing` is `true`, is renders a `submit` button.

**Comment by brandonpittman** [comment]
@edmundhung 

I'm conditionally changing the button's `type`. When the type changes to `submit`, validation fires.
