### ISSUE TITLE
Property 'getFieldset' does not exist on type 'FieldMetadata'

### ISSUE THREAD

**Issue by binajmen** [edmundhung/conform#499]
### Describe the bug and the expected behavior

I have a simple form:
```ts
  const [form, fields] = useForm({
    lastResult,
    defaultValue: user,
    shouldValidate: "onBlur",
    onValidate({ formData }) {
      return parseWithZod(formData, { schema: dataSchema });
    },
  });
  const profile = fields.profile.getFieldset();
```
The LSP and `lint` does not report an error. However, `typecheck` is:
```
error TS2339: Property 'getFieldset' does not exist on type 'FieldMetadata<JsonifyObject<{ createdAt: Date; userId: string; ... }> | null, JsonifyObject<...>, string[]>'.
```

### Conform version

1.0.2

### Steps to Reproduce the Bug or Issue

Run `typecheck` while using `getFieldset`

**Comment by edmundhung** [comment]
Can you please share your zod schema?

**Comment by aaronadamsCA** [comment]
I'm seeing the same issue upgrading from v1.0.0 to v1.0.2.

Here's a short repro:

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMBix0BsAmcAvnAGZQQhwBEAAgMYQB2p0IAtDBAPRToCG9GNQDcAKDHAmMdFFKD0cAMr0AFuhD9EYuGQgQAXHFQwoUgObiiEgBQBKOAF4AfNt2MmJuAG0k59DDYePgY8EQAuk4oGEEEADwq6prONtRM-CDo1Hbi7sxeSKwQxFH+gTgEofZW4mLc3HAA6tAA1vwUyEz4YvZOrgg6cB5evnBlsSEBxJGO0VgV+HGF+kYmZkzmxClpGVk5g8Pwy8Uks+MLVftE4kA

```ts
import { useField } from "@conform-to/react";

interface Schema {
  foo: string;
}

() => {
  const [{ getFieldset }] = useField<Schema>("name");
  const { foo } = getFieldset();
};

// Workaround
() => {
  const [{ getFieldset }] = useField<{ foo: string }>("name");
  const { foo } = getFieldset();
};
```

The problem is that an `interface` without an index signature never `extends Record<string, unknown>`. I suspect the correct check may simply be `extends object`.

**Comment by edmundhung** [comment]
> The problem is that an interface without an index signature never extends Record<string, unknown>.

I have never thought about this 🤔 Interesting.

> I suspect the correct check may be extends object.

Feel free to submit a PR if you have any ideas. I did some changes to improve the type inference on #459 recently but I am also uncertain if I covered all possible cases.

> I don't understand why an entire schema would ever be null or undefined

I think part of the issue is the same as #478 in which TS infers the schema based on the default value instead. But your solution looks good to me.

**Comment by aaronadamsCA** [comment]
@edmundhung, I've filed #508 with the solution I described, plus updated tests.

**Comment by edmundhung** [comment]
Thank you @aaronadamsCA! I am busy with something else right now but I wish to come back to it later this week and will likely cut a release with a few other fixes. :)

**Comment by binajmen** [comment]
Apologies for the delayed response. I've observed that the issue arises when a default value is supplied in an incorrect format. However, it's unclear why this impacts `getFieldSet`. Since this seems to be a user-related issue, I don't believe further investigation is necessary.

**Comment by rexebin** [comment]
> Apologies for the delayed response. I've observed that the issue arises when a default value is supplied in an incorrect format. However, it's unclear why this impacts `getFieldSet`. Since this seems to be a user-related issue, I don't believe further investigation is necessary.

Yes I can confirm the type infer is from the default value type. if we properly type the field in question as an object, `getFieldSet()` will be inferred.
