### ISSUE TITLE
Uncaught Error: The submit event is dispatched by form#a instead of form#b

### ISSUE THREAD

**Issue by marilari88** [edmundhung/conform#587]
### Describe the bug and the expected behavior

When attempting to submit a form within a radix-ui dialog, I encountered an error message in the console: "Uncaught Error: The submit event is dispatched by form#b instead of form#a". The form#a resides within the dialog.

To illustrate this issue, I've provided a reproducible example here: [link](https://stackblitz.com/~/github.com/marilari88/conform-with-dialog).

It appears that despite only submitting form#a, the submit event handler of form#b is triggered.

### Conform version

v1.1.0

### Steps to Reproduce the Bug or Issue

1. Open [https://stackblitz.com/~/github.com/marilari88/conform-with-dialog](https://stackblitz.com/~/github.com/marilari88/conform-with-dialog) or clone locally if you prefere [this](github.com/marilari88/conform-with-dialog)
2. Press 'add player'
3. Fill the name and goal field
4. Submit

### What browsers are you seeing the problem on?

Chrome

### Screenshots or Videos

![conform error](https://github.com/edmundhung/conform/assets/32909388/dc2df843-15f5-41cb-a8b7-e8679cf50852)

**Comment by edmundhung** [comment]
Interesting! This might be a bug on React? It can be resolved by moving the dialog out of the team form. Although the dialog will renders the player form outside of the team form, but the react submit event still bubbles up through the virtual dom, which triggers the `onSubmit` handler on the team form and trigger the error you had.

**Comment by houmark** [comment]
Nested forms is not allowed in HTML, so that appears to be the base reason for the error.

I read in the docs that you should be able to use a [FormProvider/FormContext](https://conform.guide/api/react/FormProvider#tips) in Conform to control which form you submit, but I have not tested this myself and wonder why @edmundhung did not suggest that as a solution, so maybe I am misunderstanding something here. If that's the case, then please disregard, but just wanted to mention a possible solution if you are not able to move your dialog outside the parent form.

**Comment by penx** [comment]
I think you can use stopPropagation to solve this?

```ts
const [form, fields] = useForm({
  id: useId(),
  onSubmit: (e, context) => {
    // do what you need
    e.stopPropagation();
  },
});
```

**Comment by penx** [comment]
I've also encountered this issue today. Our use case is we have a large form, some buttons within it that open a modal.

The modal contains a small form, representing a part of the parent form data. The user can fill this in or cancel out of the modal. This is a different form as, if the user cancels out, it should not affect the data of the parent form.

As explained above, this is valid html as the child form is within the React component tree but not the DOM of the parent form.

We make use of `useInputControl`'s `change` to update the parent form when the modal form is submitted.

We want to use conform for both forms to keep validation and data structure consistent.

I have't yet found a solution other than using `e.stopPropagation`.

Other things I've tried that don't seem to work:

- setting form={form.id} on the submit button
- removing the `type=submit` from the button and calling `conformFormProps.onSubmit` directly

**Comment by edmundhung** [comment]
Nested form tag is a bad practice in general so it is probably better to avoid it even your Dialog might render it outside. Conform has full support of form attribute and is utilizing the formId generated to make sure all your inputs and intent button works no matter they are enclosing within the form tag. You should be able to keep it working like this:

```tsx
export function Component() {
  const [form, fields] = useForm({
    // ...
  });

  return (
    <>
       <Form {...getFormProps(form)} />
       <input {...getInputProps(fields.example)} />
       <button form={form.id}>Submit</button>
    </>
  );
}
```

I am converting this to an discussion since the issue wasn't a bug in Conform.
