### ISSUE TITLE
Error: Unsupported schema

### ISSUE THREAD

**Issue by juanbercoff** [edmundhung/conform#605]
### Describe the bug and the expected behavior

I'm encountering an issue when using getZodConstraint with a zod schema defined in a package in a monorepo. When copying and pasting the schema it' works as expected, when using the imported schema it throws "Error: Unsupported schema".

```ts
The schema is a simple zod object with z.string types, like:
export const basicSchema = z.object({
  userName: z.string().min(2),
  userEmail: z.string().email(),
});
```

I'm bundling the package with tsup like `tsup ./src/index.ts --format cjs,esm --dts`

Let me know if you need additional information.

### Conform version

1.1.2

### Steps to Reproduce the Bug or Issue

1. A monorepo with a schema package
2. Importing the schema
3. Using getZodConstraint on it

**Comment by juanbercoff** [comment]
@edmundhung This issue is resolved by commit b4d481790f1799c7a9fd72abb4b5f4faf1125448

Could we have a release?

**Comment by edmundhung** [comment]
I should have a patch release in a couple days. But keep in mind the root clause you run into is likely caused by misconfiguration on your setup and so there are several copies of zod bundled. This fix only get rid of the superficial problem but you are still serving different copies which might have your app run into other issues in long term.

**Comment by edmundhung** [comment]
The [patch](https://github.com/edmundhung/conform/releases/tag/v1.1.3) is out.
