### ISSUE TITLE
Can't catch error on list validation

### ISSUE THREAD

**Issue by kokotom** [edmundhung/conform#62]
I tried to add validation to the length of a list of objects (using zod's refine method).
When checking the output of `parse` I see that the input is indeed invalid but the `error` retuning from `useFieldset` is missing.

Here is a reproduction:

https://codesandbox.io/s/dreamy-ioana-qmyp8d?file=/src/App.tsx

I was expecting to see an error message for the list being too short but the submissions fails silently.

**Comment by edmundhung** [comment]
Hi @kokotom. Thanks for raising the issue and merry xmas!

Part of the issue here is that all error has to have a corresponding element for the Constraint Validation API to be effective. This can be solved manually by adding a hidden button with the corresponding name on the dom. e.g. `<button hidden name="tasks" />`. It will also be resolved in the next version as conform will create it for you automatically.

However, it looks like the current implementation accidentally skips the validation when modifying a list as well, causing the error to be populated only on submit and won't be cleared until it is submit again. I will revisit the validation flow and come back to you next week.

**Comment by kokotom** [comment]
Thanks for clarifying!
Merry xmas 😄 🎄

**Comment by edmundhung** [comment]
Fixed on [v0.6.0](https://github.com/edmundhung/conform/releases/tag/v0.6.0).
