### ISSUE TITLE
schema not allowing empty string through

### ISSUE THREAD

**Issue by lifeiscontent** [edmundhung/conform#676]
### Describe the bug and the expected behavior

https://stackblitz.com/edit/remix-run-remix-fd6e6f?file=app%2Froutes%2F_index.tsx,app%2Fentry.client.tsx

I'd expect being able to press "Submit" to work because the default value of inputs is `""`

### Conform version

v.1.1.4

### Steps to Reproduce the Bug or Issue

1. Goto the stackblitz page
2. press enter
3. see validation error instead of submission

**Comment by edmundhung** [comment]
This is working by design. You can find an [explanation](https://github.com/edmundhung/conform/discussions/637#discussioncomment-9394588) here.

**Comment by lifeiscontent** [comment]
@edmundhung in order to support empty strings I've had to use `z.string().optional().default("__EMPTY_STRING__").transform(value => typeof value === undefined || value === "__EMPTY_STRING__" ? "" : value);`

this seems like a bit of a footgun, any ideas on how to make this a bit easier to handle?

**Comment by edmundhung** [comment]
> @edmundhung in order to support empty strings I've had to use `z.string().optional().default("__EMPTY_STRING__").transform(value => typeof value === undefined || value === "__EMPTY_STRING__" ? "" : value);`

Is the `.default()` necessary? I believe `.transform(value => value ?? '')` would be enough

**Comment by lifeiscontent** [comment]
@edmundhung you're right, is there a reason why `z.string()` works differently than other types?

I'd expect `z.string().optional().default('')` to work as well, since it works with all other types too such as `z.number`, `z.boolean`, etc

**Comment by edmundhung** [comment]
It is because `.default()` runs before the coercion and so defaulting to empty string will still result in `undefined` here. But I can see how the inconsistency here will trap many people.

I can add additional logic to handle this case. But I wonder if `.default('')` is really what we want here. As the default value will still be validated. If you have a email schema like `z.string().email().default('')`, you will end up with a invalid email error. While `z.string().email().optional().transform(value => value ?? '')` would not have such issue.

**Comment by lifeiscontent** [comment]
@edmundhung I believe in the case where you have a larger schema that has a union the default will still pass the object validation and then the individual email check will happen, you can see an example of this in the schema I sent you on discord.
